on:
  push:
    branches:
      - master

    paths:
        - 'src/**'
        - '.github/workflows/publish-docs.yml'
        - 'package.json'
        - 'pnpm-lock.yaml'
        - 'vite.config.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build-docs

      - name: Commit and push changes
        run: |
          if [[ -n $(git status -s) ]]; then
              git config --global user.email "vue3ytframe@users.noreply.github.com"
              git config --global user.name "Vue3 Ytframe Bot"
              git commit -am "Update docs $(date -Iseconds)"
              git push
          fi
